# Generated by Django 5.0.7 on 2024-07-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makevideo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
